<?php

use Drupal\Core\Database\Database;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_cron().
 */
function alternative_revisions_cron() {
    
}

/**
 * Implements hook_theme().
 */
function alternative_revisions_theme($existing, $type, $theme, $path) {
    return [
        'alternative_revisions_view_revisions' => [
            'variables' => [
                'data' => NULL,
                'headers' => NULL,
                'nid' => NULL,
            ]
        ]
    ];
}

/**
 * Implements hook_entity_insert().
 */
function alternative_revisions_entity_insert(EntityInterface $entity) {
    if ($entity instanceof NodeInterface) {
        $revisions_manager = \Drupal::service('alternative_revisions.revision_update_manager');
        $original = $entity->original;
        $revisions_manager->checkForRevisions($entity, $original);
    }
}

/**
 * Implements hook_entity_update().
 */
function alternative_revisions_entity_update(EntityInterface $entity) {
    if ($entity instanceof NodeInterface) {
        $revisions_manager = \Drupal::service('alternative_revisions.revision_update_manager');
        $original = $entity->original;
        $revisions_manager->checkForRevisions($entity, $original);
    }
}

/**
 * Implements hook_entity_field_storage_info_alter().
 */
function alternative_revisions_entity_field_storage_info_alter(&$fields, EntityTypeInterface $entity_type) {
    if ($entity_type->id() == 'node') {
        $database = Database::getConnection();
        $schema = $database->schema();
        $revisions_manager = \Drupal::service('alternative_revisions.table_creation_manager');
        if ($revisions_manager) {
            foreach ($fields as $field_name => $field) {
                $table_name = 'node_alt_revision__' . $field_name;
                if (!$schema->tableExists($table_name)) {
                    $field_type = $field->getType();
                    $revisions_manager->createDatabaseTable($field_name, $field_type, $table_name);
                }
            }
        }
    }
}